// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXJVlBKwSKN4uHbKN2VK_7PJb6wBx3mzE',
    appId: '1:825635816619:android:c01edc8a1d17e11095a3ee',
    messagingSenderId: '825635816619',
    projectId: 'fintrack-2703e',
    storageBucket: 'fintrack-2703e.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI05xLhQ-7DyM1Cv7ctU1js6mPSY0AeP4',
    appId: '1:825635816619:web:ff850d30b8f5e4a395a3ee',
    messagingSenderId: '825635816619',
    projectId: 'fintrack-2703e',
    authDomain: 'fintrack-2703e.firebaseapp.com',
    storageBucket: 'fintrack-2703e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR4Zf_yTFfLnFAsKRVuBGeW3oo4ikgOVE',
    appId: '1:825635816619:ios:e3f5b3f3f27d615c95a3ee',
    messagingSenderId: '825635816619',
    projectId: 'fintrack-2703e',
    storageBucket: 'fintrack-2703e.firebasestorage.app',
    iosBundleId: 'com.fintrack.fintrack',
  );
}
